name: Package Mac GUI
on:
  push:
    tags:
      - 'v*'

jobs:
  bundle-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Ensure binary is executable
        run: chmod +x spec_gen_mac

      - name: Install Python Dependencies
        run: |
          pip install pyinstaller numpy matplotlib

      - name: Bundle with PyInstaller
        run: |
          # --add-data "source_file:destination_inside_app"
          # On Mac, the separator is a colon ":"
          pyinstaller --onefile --noconsole --add-data "spec_gen_mac:." src/viewer/gui.py

      - name: Upload Mac Executable
        uses: actions/upload-artifact@v4
        with:
          name: pluspam-macos
          path: dist/gui